[package]
name = "mica"
version = "0.1.0"
edition = "2024"
authors = ["Arane Aimer"]

[dependencies]
tokio = { version = "1.37", features = ["full"] }
clap = { version = "4.5", features = ["derive"] }
anyhow = "1.0.98"
gstreamer = "0.23.7"
gstreamer-rtsp-server = "0.23.5"
glib = "0.20.12"

