[package]
name = "mica"
version = "0.1.0"
edition = "2024"
authors = ["Arane Aimer"]

[dependencies]
tokio = { version = "1.37", features = ["full"] }
clap = { version = "4.5", features = ["derive"] }
cpal = "0.16.0"
opus = "0.3.0"

